#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: pass help [--usage] COMMAND

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help pass
fi

lasher _help pass "$command"
