#!/usr/bin/env bash

set -e

echo -n "User name: "
read name

echo -n "E-mail: "
read email

pass-_gpg --gen-key --batch <<KEYDATA
Key-Type: RSA
Key-Length: 2048
Name-Real: ${name}
Name-Comment: pass#$(hostname -s)
Name-Email: ${email}
Expire-Date: 0
%no-protection

%commit
KEYDATA

echo
echo "Saving public key to $(hostname -s)_key.gpg"
echo

pass-_gpg --export --armor "(pass#$(hostname -s)) <${email}>" > "$(hostname -s)_key.gpg"
