#!/usr/bin/env bash
#
# Summary: Read a password to the store
#
# Usage: pass read <domain>

domain="$1"

if [ -z "$domain" ]; then
  pass-help read
  exit 1
fi

pass-_check-store

pass-_gpg -d "${PASS_STORE}/passwords/$domain" | head -n 1
