#!/usr/bin/env bash
#
# Summary: Add a password to the store
#
# Usage: pass add [-f] <domain>

force=false

while getopts ":f" opt; do
  case $opt in
    f)
      force=true
      ;;
    \?)
      echo "pass: invalid option"
      exit 1
      ;;
  esac
done

shift $(( OPTIND-1 ))

domain="$1"

if [ -z "$domain" ]; then
  pass-help add
  exit 1
fi

pass-_check-store

if [ -e "${PASS_STORE}/passwords/$domain" ]; then
  if [ "$force" = true ]; then
    rm "${PASS_STORE}/passwords/$domain"
  else
    echo "pass: password already exists"
    exit 1
  fi
fi

read -r -p "Password: " -s password

devices="$(pass-list-devices --porcelain)"

recipients=()
for device in $devices; do
  recipients+=( "-r" "pass#${device}" )
done

mkdir -p "${PASS_STORE}/passwords/$(dirname "$domain")"

pass-_gpg -e "${recipients[@]}" --trust-model always -o "${PASS_STORE}/passwords/$domain" <<<"$password"
