#!/usr/bin/env bash
#
# Summary: Initialize the password store
#
# Usage: pass init

if [ -e "${PASS_STORE}" ]; then
  echo "pass: store already initialized at ${PASS_STORE}"
  exit 1
fi

echo -n "User name: "
read name

echo -n "E-mail: "
read email

mkdir -p "${PASS_STORE}/passwords"
touch "${PASS_STORE}/keyring.gpg"

pass-_gpg --gen-key --batch <<KEYDATA
Key-Type: RSA
Key-Length: 2048
Name-Real: ${name}
Name-Email: ${email}
Expire-Date: 0
${KEY_PROTECTION}

%commit
KEYDATA

echo "pass: store initialized at ${PASS_STORE}"
