#!/usr/bin/env bash
#
# Summary: Lists all stored passwords
#
# Usage: pass list

set -e

pass-_check-store

opt="$1"

porcelain=false
if [ -n "$opt" ]; then
  if [ "$opt" = "--porcelain" ]; then
    porcelain=true
  fi
fi

if [ "$porcelain" = true ]; then
  (
    cd "${PASS_STORE}/passwords"
    find . -type f | sed "s|^\./||"
  )
  exit
fi

tree -l --noreport "${PASS_STORE}/passwords" | tail -n +2

