#!/usr/bin/env bash
#
# Summary: Initialize the password store
#
# Usage: pass init

if [ -e "${PASS_STORE}" ]; then
  echo "pass: store already initialized at ${PASS_STORE}"
  exit 1
fi

mkdir "${PASS_STORE}"
touch "${PASS_STORE}/keyring.gpg"

echo "pass: store initialized at ${PASS_STORE}"
